### ISSUE TITLE
Add user doc

### ISSUE THREAD

**Issue by gpetit** [geobretagne/mviewer.doc#2]
Add user doc for :
- [x] Gestionnaire de couches
- [x] Gestion de l'affichage
- [x] Outils de navigation
- [x] Outils additionnels
- [x] Fond de carte
- [x] Crédits

**Comment by gpetit** [comment]
@spelhate for the moment, you can assign to myself this issue.

I'm currently working on "Outils additionnels"

**Comment by gpetit** [comment]
Now, I'm working on "navigation", "maps" and "credits"

**Comment by gpetit** [comment]
Next step, manage and display layers

**Comment by gpetit** [comment]
Issue Done. 
@spelhate you are invited to close this issue if the result is ok for you.

**Comment by spelhate** [comment]
Thank's a lot @gpetit. I close this issue.
