### ISSUE TITLE
Push -f dans git.rst

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer.doc#20]
Le fichier git.rst présente comme mécanisme de remontée de commits la commande push -f.
J'ai l'impression que ce n'est pas une bonne pratique du tout pour deux raisons :

1. Faire un push -f peut écraser l'historique si l'auteur a commis une erreur lors des manipulations qui précèdent. Selon moi l'option -f ne devrait être utiliser que pour justement corriger une grosse boulette : une erreur de manipulation précédente ou pour masquer des données confidentielles que l'on ne devrait pas voir dans github.

2. Faire un push directement sur master ne devrait pas être la règle. Nous devrions plutôt privilégier les pull requests.

**Comment by spelhate** [comment]
Personnellement, je ne n'utilise pas la commande `push -f`.
Ok sur l'e fait de privilégier les PR.

**Comment by Gaetanbrl** [comment]
Avis partagé.

Attention, la commande de push n'est précisée que pour le rebase de sa branche feature dans notre gitflow. Par vers la master.

Un rebase ne devrait pas avoir lieu sur la branche master.

**Comment by bchartier** [comment]
> Attention, dans le fichier git.rst, la commande `push -f` n'est précisée que pour réaliser un rebase dans sa branche de travail (ex: feature dans notre gitflow). Pas vers la master.

Oui, effectivement. Cela ne devrait donc pas poser de problème.
De mon côté je suis perturbé parce le remote et le nom de la branche n'apparaissent pas souvent dans les exemples de la doc.
Dans ma config :
- je me débrouille pour avoir systématiquement pour que le nom de la branche courante dans le prompt de ma fenêtre terminal
- je mets systématiquement le nom du remote et de la branche dans mes commandes push

Je ferme ce ticket.
