### ISSUE TITLE
Template class="item"

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer.doc#21]
Insert more accurate infos about class="item".

Link to geobretagne/mviewer#207.

https://github.com/geobretagne/mviewer/blob/3d21b02c2390e8c25f85412d3db02f5beb51c072/js/info.js#L94

**Comment by Gaetanbrl** [comment]
@spelhate could you give me some right to assign me on this issue ?

**Comment by spelhate** [comment]
It's in the doc here : https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_tpl.html
