### ISSUE TITLE
Mettre à jour la section syntaxe theme

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer.doc#30]
https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_layers.html#syntaxe-theme

Compléter cette section pour prendre en compte le paramètre l'évolution https://github.com/geobretagne/mviewer/issues/112

**Comment by spelhate** [comment]
En lien avec https://github.com/geobretagne/mviewerstudio/issues/19

**Comment by spelhate** [comment]
@Gaetanbrl , je me rends compte que le paramètre legendmini n'est pas documenté dans cette section.

**Comment by Gaetanbrl** [comment]
@spelhate issue #26 en attente pour ce paramètre.

**Comment by spelhate** [comment]
Ok. je ferme celle ci. https://github.com/geobretagne/mviewer.doc/commit/11cdc334b2cd7721a5c55125cea4dea227d84909
